### ISSUE TITLE
Accessing the gulp-clean-css via the gulp-load-plugins

### ISSUE THREAD

**Issue by sonnyk22** [scniro/gulp-clean-css#11]
I am having an issue accessing the gulp-clean-css via the gulp-load-plugins.

For example:
```
    var $ = require('gulp-load-plugins')({ lazy: true }),
    ...
    return gulp
            .src(cssPath)
            .pipe($.size())
            .pipe($.clean-css())
```
I tried both using $.clean-css() or $.cleancss(), but was unsuccessful.

Would you please help me with this?

**Comment by sonnyk22** [comment]
got it working.  

`.pipe($.cleanCss())`

**Comment by scniro** [comment]
🎉 👍

**Comment by georgebuzoianu** [comment]
Hello!
Documentation for "Accessing the gulp-clean-css via the gulp-load-plugins" still missing from official README :(
