### ISSUE TITLE
[Question] Production Ready?

### ISSUE THREAD

**Issue by erwstout** [scniro/gulp-clean-css#13]
Hi @scniro! 

I've been following this project closely since our team initially used it before it became depreciated and you took over and I applaud you for your work! Sorry for opening an issue to ask this (I kinda wish GitHub had some sort of a message board/communication feature) but what is the current state of the plugin? Would it be recommended for production use yet? I know you've been hard at work getting some of the dust and bugs off. Thanks!

**Comment by scniro** [comment]
@erwstout hey! No worries contacting me here, but I'm pleading right there with you for direct messaging from github. I'd say you'd be okay to use this, as many projects are using it right now. I try to keep the latest clean-css dep in the package and this plugin isn't really not all that much code - I'd say march forward with it.

The only issues I'm still being plagued by all involve source maps. If you check out some of the open issues, they almost all involve source maps of some sort. It's just been a rabbit hole, as I can't reproduce any of the issues and when I've asked for reproduction sample projects - I still can't get a consistently failing sample.

All this sourcemapping madness is on my radar, I can assure - though it's just been like throwing darts in the dark so far.

So, aside from edge case sourcemapping ... 👍

**Comment by erwstout** [comment]
Perfect, thanks! Keep up the good work. I'll play around with it a bit and see if I have any issues with source mapping and contribute what I can. Take care!
