### ISSUE TITLE
Callback only called for a single file

### ISSUE THREAD

**Issue by gamebox** [scniro/gulp-clean-css#16]
I have the following setup(minimum representation):

``` javascript
var cssPipeline = lazypipe()
      .pipe(function() {
        return $['if'](minifyCss, $.cleanCss({debug: true}, function(details) {
          console.log("Original size of " + details.path + ": " + details.stats.originalSize);
          console.log("Minified size of " + details.path + ": " + details.stats.minifiedSize);
        }));
      });

  var sources = ...; // Some array of globs that in total represents four CSS files

  return gulp.src(sources)
    .pipe($.sourcemaps.init())
    .pipe($.groupConcat(GROUP_CONCAT_CONFIG))
    .pipe($['if']('*.css', cssPipeline()))
    .pipe(sourceMapsWrite());
});
```

And the output is 

```
Original size of app/css/admin.css: 194062
Minified size of app/css/admin.css: 189246
```

And that is all.  All of the files that should be minified are, but the callback was only called once.  I actually don't need this callback, was just interested in the output, but I thought you might want to fix this for other users

**Comment by scniro** [comment]
@gamebox  Hmh, I am not terribly familiar with `lazypipe`, but glancing at this structure and if I am not mistaken, it appears you are concatenating via `groupConcat` _before_ you clean. If so, you're cleaning now one file hence the one callback. What if you cleaned before you concatenated?
