### ISSUE TITLE
"File already exists" error when processing CSS before minification

### ISSUE THREAD

**Issue by fsmaia** [scniro/gulp-clean-css#18]
Since version 2.1.1, when using `gulp-clean-css` piped after `gulp-sass`, like in the example below, I'm getting this error: `Error: EEXIST: file already exists, mkdir...`.
```js
const gulpCleanCSS = require('gulp-clean-css');
const gulpSass = require('gulp-sass');

exports.fn = function(gulp) {
    gulp
        .src(['assets/sass/**/*'])
        .pipe(gulpSass())
        .pipe(guplCleanCSS())
        .pipe(gulp.dest('app/public/css'))
};
```

Probably this errors occurs everytime that `gulp-clean-css` is not the first processing task.

May I be helpful somehow in order to fix this?

Thank you in advance.

**Comment by scniro** [comment]
do you have anything in your `assets/sass/` directory _besides_ `.scss` files. Would specifying `gulp.src(['assets/sass/**/*.scss'])` with the file extension help? I just mocked out a test and all succeeds as expected...

```
it('should play nicely with other plugins: gulp-sass: before', function (done) {
    var i = 0;

    gulp.src('test/fixtures/**/*.scss')
      .pipe(gulpSass())
      .pipe(cleanCSS())
      .pipe(gulp.dest('test/fixtures/'))
      .on('data', function (file) {
        i += 1;
      })
      .once('end', function () {
        i.should.equal(3);
        done();
      });
  });
``` 

where 

a.scss =>

`$color: red;`

b.scss =>

```
@import 'a.scss';

span {
  color: $color
}
```

test-sass.scss =>

```
@import 'a.scss';
@import 'b.scss';
```

results in the correct css being generated and minifed for the correct files. Could you create a spall, reproducible example?

**Comment by fsmaia** [comment]
I created a [repository](https://github.com/fsmaia/gulp-clean-css-issue-18) with empty SASS files, and the problem is exactly not having the extension in `gulp.src` pattern, as shown [here](https://github.com/fsmaia/gulp-clean-css-issue-18/blob/master/Gulpfile.js#L8).

In this case, the directories are becoming empty files in CSS output. Then two files in the same directory are generating the same output file (with directory name) and then the `mkdir` error occurs.

**Comment by scniro** [comment]
@fsmaia I was able to reproduce this thanks to your sample repo. I added a simple check which fails fast and passes the file along should a situation like this be encountered...

```
if (!file || !file.contents)
      return cb(null, file);
```

[2.2.1](https://www.npmjs.com/package/gulp-clean-css) published. Can you please install and verify if resolved on your end?

**Comment by scniro** [comment]
yikes hold off, my CI is failing :/

**Comment by scniro** [comment]
nevermind we're good. Accidentally snuck in some native es6 syntax in my tests

https://travis-ci.org/scniro/gulp-clean-css/builds/182731687

Let me know on your end so I can close this out if we're good

**Comment by fsmaia** [comment]
Problem fixed! Thank you!
