### ISSUE TITLE
Error: Cannot find module 'gulp-concat'

### ISSUE THREAD

**Issue by rgerstenberger** [scniro/gulp-clean-css#19]
I hit this build error. It looks like `gulp-concat` was added to `index.js` but still remains in `devDependencies`. From this recent commit: https://github.com/scniro/gulp-clean-css/commit/3104238c01fb0ebc5b32c0d61cf13788f9339b4d#diff-168726dbe96b3ce427e7fedce31bb0bcR7

I can add `gulp-concat` to my project's `devDependencies` to get around this but others may hit the same issue. Perhaps `gulp-concat` should be a strict `dependency`.

```
Error: Cannot find module 'gulp-concat'
```

Thanks for the project, and keep up the good work :)

**Comment by tomlutzenberger** [comment]
Ran into the same issue :(
Thx for the devDependencies hint

**Comment by scniro** [comment]
sorry guys, that's me being dumb from earlier. Left that in there, it's definitely not a dependency, though I do use it for testing. Sorry! standby for a publish...

**Comment by scniro** [comment]
[2.1.3 published](https://www.npmjs.com/package/gulp-clean-css) - sorry!

**Comment by tomlutzenberger** [comment]
That was pretty quick, thanks a lot 😀
