### ISSUE TITLE
Broken @import

### ISSUE THREAD

**Issue by darlanmendonca** [scniro/gulp-clean-css#25]
when I have @import in css, this module broken :(

you want add support to this?

is css3 import (I believe), the doc of this feature, I found here https://developer.mozilla.org/pt-BR/docs/Web/CSS/@import

```css
@import url(https://fonts.googleapis.com/css?family=Fira+Mono);
```

**Comment by scniro** [comment]
Can you clarify what you mean by broken? Can't see any issue here. I'd also suspect if there is indeed any issue, it'll be related to [clean-css](https://github.com/jakubpawlowicz/clean-css)

**Comment by SlippySken** [comment]
Maybe it is related to this?

[Issue 865 in clean-css](https://github.com/jakubpawlowicz/clean-css/issues/865)
