### ISSUE TITLE
does not work as per docs

### ISSUE THREAD

**Issue by ichepurnoy** [scniro/gulp-clean-css#3]
Dear @scniro ,
I am unable to get ```gulp-clean-css``` to minify css files.
It does something to them, but it's not minification, on the contrary: for example, a minified file would get kind of 'unminified'.
At the same time, by using ```clean-css``` command in Bash, like 
    ```cleancss file.css -o file.min.css```
I am getting a minified file, as expected.

What am I missing, how do I use your ```gulp-clean-css``` for minification?

**Comment by scniro** [comment]
@ichepurnoy Can you share some code? Not totally sure what is going on here based on your explanation alone. Thanks!

**Comment by ichepurnoy** [comment]
I'm sorry  I'm a novice with Gulp so far. Here's my gulpfile.js:
```
'use strict';

var gulp        = require('gulp'),
    concatCss   = require('gulp-concat-css'),
    cleanCSS    = require('gulp-clean-css'),
    autoprefixer= require('gulp-autoprefixer');


gulp.task('default', function(){
     return gulp.src('css_new/home.css')

        .pipe(cleanCSS({debug: true}, function(details) {
             console.log(details.name + ': ' + details.stats.originalSize);
             console.log(details.name + ': ' + details.stats.minifiedSize);
         }))
         .pipe(autoprefixer({
             browsers: ['last 3 versions'],
             cascade: false
         }))
        .pipe(concatCss("total.css"))
        .pipe(gulp.dest('css_min/'));
    
});
```

The code from like ```.banners{overflow:hidden;position:relative;clear:both}```
is transformed into 
    .banners {
  overflow: hidden;
  position: relative;
  clear: both;
}

**Comment by scniro** [comment]
@ichepurnoy No worries, from what I can tell this seems to be due the `autoprefixer` call _after_ minifying the css. Try prefixing _before_ that call, as such...


    .pipe(autoprefixer({
         browsers: ['last 3 versions'],
         cascade: false
     }))
    .pipe(cleanCSS({debug: true}, function(details) {
         console.log(details.name + ': ' + details.stats.originalSize);
         console.log(details.name + ': ' + details.stats.minifiedSize);
     }))
    /*[...]*/

**Comment by ichepurnoy** [comment]
Thanks for quick response)
No, no effect. I've even commented  autoprefixer out, but to no avail.
Should  ```clean-css``` be also installed along with ```gulp-clean-css```?

**Comment by scniro** [comment]
I just tried it with the sample css in question and the result was as expected. Are you concatenating one source file? I'd expect to see an array of sources. Try minifying one css file and simply `.dest` it out, removing any other plugin interference. `gulp-clean-css` comes bundled with `clean-css` as a dependency so there is no need to manually use that library in the gulp pipeline. I'm suspecting the issue in question is not due to this plugin itself, but I'll certainly help you get through this if you keep sharing details

**Comment by ichepurnoy** [comment]
Oh, I found it, by taking things out step-by-step. It was ```gulp-concat-css```, not autoprefixer, but your hint was in right direction)  I need to look into its docs, maybe this is expected behaviour for it, dunno.
Big thanks for spending your time on me, @scniro !

**Comment by scniro** [comment]
np at all! Best of luck :)
