### ISSUE TITLE
How to remove spaces and blank lines in css file with gulp-clean-css ?

### ISSUE THREAD

**Issue by titancat** [scniro/gulp-clean-css#30]
In the past I used `gulp-minify-css` to remove spaces and black lines. 
Here is my gulpfiles.js code segment.

```js
gulp.task('css', function () {
  return gulp.src('./css/**/*.css')
    .pipe(minifycss({
            compatibility: 'ie7'
        }))
    .pipe(gulp.dest('./build'));
});
```
It worked well.

Now I try to use  `gulp-minify-css` replace with  `gulp-clean-css`.

```js
gulp.task('css', function () {
  return gulp.src('./css/**/*.css')
    .pipe(plumber())
    .pipe(autoprefixer({
        browsers: ['> 5%']
    }))
    .pipe(cleanCSS({
        advanced: false,
        compatibility: '',
        keepBreaks: false,
        keepSpecialComments: 0
    }))
    .pipe(gulp.dest('./build'));
});
```
It can not achieve the desired effect.  Where did I make the mistake? 
What should I do?

**Comment by erwstout** [comment]
This may be an issue that would need to be posted on https://github.com/jakubpawlowicz/clean-css/tree/3.4 - may not be an issue with the wrapper itself. It looks fine to me... Thoughts? @scniro

**Comment by scniro** [comment]
@erwstout that's what I am thinking as well. I see the "never" task has significantly different options passed to it. @titancat can you clarify what your expected result is? I assume you just with to minify the css but am unsure. I'd start by just removing the options to see what you get, but yes, if there is a minification error you'd want to investigate with [clean-css](https://github.com/jakubpawlowicz/clean-css) itself.

**Comment by titancat** [comment]
@scniro @erwstout Maybe I should open an issue on [clean-css](https://github.com/jakubpawlowicz/clean-css).
