### ISSUE TITLE
Release versions, tags and CHANGELOG do not match

### ISSUE THREAD

**Issue by normanjaeckel** [scniro/gulp-clean-css#32]
At the moment the latest release is 2.3.2 but the CHANGELOG says 2.3.1. (I think the content of the 2.3.1 section was meant to be 2.3.2 and for 2.3.1 a CHANGELOG entry is missing) Also the GitHub tags and [releases](https://github.com/scniro/gulp-clean-css/releases) do not exist.

Nevertheless a nice package. :-)

**Comment by scniro** [comment]
hehe, thanks for that! However, I'm going to close this out as it's not too much of an issue in the sense of something being defective - rather me being slightly moronic 😜. If it bothers your sanity too much I'd welcome your contributions if you'd like to clean this up!

**Comment by normanjaeckel** [comment]
You just released 2.4.0 and this looks good overall for this version. So everything is fine. Thanks.

(Hint: You just added `npm-debug.log` to the repository – possibly accidentally.)

**Comment by scniro** [comment]
goodness me lol thanks for pointing the log file. I'll delete that momentarily. And yes shortly after I posted my earlier comment I drafted a release for the current version and will be mindful to do the same moving forward. Thanks again!

**Comment by scniro** [comment]
Also to follow upm I deleted the changelog file. This project is so small - the file consisted of updates consisting of "updating clean-css dep." I don't see the urgent need to keep annotating this
