### ISSUE TITLE
Not overridden options

### ISSUE THREAD

**Issue by alosev** [scniro/gulp-clean-css#33]
Hello!
The problem arose from the fact that I override options, and the output is a file with the default settings.

http://joxi.ru/Dr8nq07H8EeG26 - css file
http://joxi.ru/E2pkaRxIN1l4mY - gulpfile
http://joxi.ru/xAee4zWTEB9BAy - output file

I expect the file to shrink, only formatted. And he shrinks and classes are grouped. I can not understand what the problem is.

**Comment by scniro** [comment]
I'd suggest opening an issue with [clean-css](https://github.com/jakubpawlowicz/clean-css) if you're experiencing issues with tweaking the options. Whatever you specify is passed through to the library.
