### ISSUE TITLE
Media queries removed

### ISSUE THREAD

**Issue by Janjuks** [scniro/gulp-clean-css#38]
Media queries are removed after minifying. In this [issue](https://github.com/scniro/gulp-clean-css/issues/31) I saw @lindevs mention the same problem, but did not get an answer, I think he wasn't understood clearly.

I have gulp-clean-css 3.0.3

My task:
```
cleanCSS = require('gulp-clean-css')
gulp.task('min-css', function () {
    return gulp.src(['CSS/**/*.css'])
    .pipe(cleanCSS())
    .pipe(rename({ suffix: '.min' }))
    .pipe(gulp.dest('CSS/min/'))
})
```

**Comment by Janjuks** [comment]
It was faulty CSS, sorry.

**Comment by scniro** [comment]
@Janjuks no worries I am glad you got it solved so quickly 😃
