### ISSUE TITLE
issue in background image path.

### ISSUE THREAD

**Issue by ckaaaa** [scniro/gulp-clean-css#40]
source:
background:url(../../images/test.png);
dest:
background:url(../images/test.png);

Thanks.

**Comment by scniro** [comment]
are you rabasing? Passing any options to clean-css? Need some more detail on what's going on here. Please share your usage

**Comment by ckaaaa** [comment]
Thanks.
you can download the tiny project and run it.
http://www.fingeredu.cn:8080/ttt.zip

the tiny project, only style files.

**Comment by scniro** [comment]
@ckaaaa any way you can post it up as a github repo? That's download link is looking all sorts of sketchy

**Comment by ckaaaa** [comment]
done.
https://github.com/ckaaaa/forcleancsstest

**Comment by rgembalik** [comment]
@scniro Hi,
I know it's kinda late response not from the owner, but have you tried giving it `{rebase:false}` as a parameter? It worked for me: `.pipe(cleanCss({rebase:false}))`. For some reason, there is rebase enabled by default and it shortens (at least for me it did) relative path, but only in certain environments - be certain I mean it works well on every env we have except for the one that is set inside docker.

**Comment by ckaaaa** [comment]
well.  Thanks. @rgembalik .
