### ISSUE TITLE
v3.3.1 breaks @import pathing

### ISSUE THREAD

**Issue by stephencorwin** [scniro/gulp-clean-css#43]
It appears as though the latest version of gulp-clean-css has a different behaviour with how it handles **@import** paths using the **inline: ['none']** option.

We unintentionally installed v3.3.1 by using the package.json devDependency declaration: **"gulp-clean-css": "^3.2.0"**.
We fixed the issue locally by changing our package.json devDependency declaration to exact: **"gulp-clean-css": "3.2.0"**.

See screenshots below

**[v3.2.0] expected result:**
![v3 2 0](https://cloud.githubusercontent.com/assets/3931162/26111747/f32ba87e-3a23-11e7-8a80-782d5df1c103.PNG)

**[v3.3.1] unexpected result:**
![v3 3 1](https://cloud.githubusercontent.com/assets/3931162/26111748/f39fa256-3a23-11e7-9ecc-a8e60c954944.PNG)

**Comment by scniro** [comment]
I think I may have a fix for this. Before I go further, can you provide me a snippet of that same css before it's minified? I'd like to see the paths beforehand

**Comment by stephencorwin** [comment]
v3.2.0 is how the URLs are without minification. Setting the **rebaseTo** option to **false** in my options doesn't seem to fix it either.

![v3 3 1-no-min](https://cloud.githubusercontent.com/assets/3931162/26113264/15ac49d6-3a28-11e7-9bc8-3c1f7f916885.PNG)

**Comment by scniro** [comment]
Interesting, I shouldn't be resolving any paths by default. Could you try to add a leading slash to your import? e.g.

    @import url('/app.min.[...]')

For some reason my test broke when I removed the leading slash with the new changes in 3.3.1. Also, `rebase` has not been surfaced yet as discussed in #42 - it should be `false` by default unless `rebaseTo` is specified. I will be surfacing `rebase` as configurable very soon should the need for it arise, but I don't suspect that'd be the cause of the issue here. Hm, leading slash...

**Comment by stephencorwin** [comment]
With leading slash.
![image](https://cloud.githubusercontent.com/assets/3931162/26114523/7e902b40-3a2b-11e7-87c9-52c66ec37760.png)

The issue here is that it is still an undesired result. I need it to respect the adjacent directory @import as it was doing previously.

**@import url(/app.min.css);**
Will try and import from the hostname root -- which doesn't work if the assets are located in an assets folder. **Ex path: "http://my-domain.com/assets/css/app.min.css"** **don't click**

Although, I could use absolute pathing as the example I just mentioned showed -- there should be no need to introduce an absolute URL here.

**Comment by scniro** [comment]
Have you tried rebasing at all, perhaps `rebaseTo: 'assets/css'`?

**Comment by stephencorwin** [comment]
Yes. As mentioned earlier, setting the rebaseTo option to **false**, **''**, or **my destination folder** doesn't seem to fix it either.

**rebaseTo: 'assets/css'**
![image](https://cloud.githubusercontent.com/assets/3931162/26118435/e97dc21c-3a37-11e7-8a63-7404bbf1c1e2.png)

What I think might be the culprit is if gulp-clean-css is somehow trying to inherit the path from **gulp.src()**. The src is directed at my sass entry point, which is referred to in a relative manor. See screenshot below.

![paths](https://cloud.githubusercontent.com/assets/3931162/26118823/410a3816-3a39-11e7-8046-bf9fd35c2d00.PNG)

Thanks again for your help on this. I appreciate it.

**Comment by scniro** [comment]
Interesting. Okay, so, everything was working for you find beforehand? I made some fundamental changes to the way the file is passes to `clean-css` for the sake of rebasing as seen here https://github.com/scniro/gulp-clean-css/commit/92ddf633773f1da24d2cb04d79dbc2f7f057a810

I wonder if, I can surface another option specific to the plugin which can flag to alternatively pass in the direct inline styles such as I was doing before? That way, we can satisfy those who need to rebase and present the option for folks to not concern themselves with it whatsoever. Perhaps something like `inlineStream: true` (hopefully to to be confused with the `inline` option from clean-css). Thoughts?

**Comment by stephencorwin** [comment]
Yes, it was working before. I was doing some digging and I'm not sure clean-css is respecting the **rebase: false** option.
Looking at: **gulp-clean-css\node_modules\clean-css\lib\reader\rebase.js**
It appears that rebase will run if rebaseAll is set to true or false. I'm not familiar enough with the codebase to know where exactly this is originating from.

But if I just return tokens from the rebase function, it works.
![with](https://cloud.githubusercontent.com/assets/3931162/26120882/46053cec-3a40-11e7-914b-9c3a88644705.PNG)

Without:
![without](https://cloud.githubusercontent.com/assets/3931162/26120893/5044b034-3a40-11e7-89c7-6a54850b0b28.PNG)

Can you verify if this is an issue with how the paths or options being set by gulp-clean-css are being passed in; or rather and issue with clean-css proper now respecting the **rebase: false** option.

**Comment by scniro** [comment]
So I looked into this a bit and the only difference your flow should be experiencing is the now passing of the file style contentsas a keyed object that clean-css expects for rebasing e.g.

```
toPass =  {
  [file.path]: {
    styles: contents
  }
};
```

Before these changes, I was passing the `contents` in directly. I am assuming there is some conflict with your processing of SASS beforehand, and then the keyed filename of that object resolving something literally that was not occurring when just the raw content was passed in. 

So, I intend to include a plugin-level option to allow to fallback to the prior passing of styles - something like `isolatePipeline: true` would pass styles, preprocessed or not, inline. Including this option should emulate the same functionality of 3.2.0. I'll get a change pushed up later on this evening and share you a locally packed up tarball to install and try out. Would that be okay?

**Comment by stephencorwin** [comment]
That sounds good.

Usually the gulp plugins I have used in the passed cater to the contents being piped in without regard to the where the content actually comes from. That is part of why they are so flexible.

```
return gulp.src('file')
.pipe(pluginA(options))
.pipe(pluginB(options));
```

if pluginA and pluginB were in reverse order, it still usually works but is a different order of operations on transforming the content. Neither plugin cares about the specifics of gulp.src() more than the contents that gulp.src() pipes in.

Providing an option to **isolatePipeline** will definitely solve this issue, but it almost feels like it is going against the grain. Perhaps it should be reversed and gulp-clean-css should be **isolatePipeline** by default with the option to explicitly state the src path for use with rebasing.

Either way works for my instance, but I would be curious to see how you and other users feel about it. Obviously, I recognize that setting default behavior can be dangerous for existing users.

Thanks for your support on this and let me know when you have something I can test locally.

**Comment by scniro** [comment]
I like your suggestion! In-versing my proposal makes sense with how you put it. Hopefully I can free up soon to get this done, at the latest, I can get the changes in by the end of the weekend - so - hopefully as a workaround until then you can keep moving forward with 3.2.0. Thank for the feedback!

**Comment by stephencorwin** [comment]
Sure thing! I edited my response early to provide a little more clarity.
Take your time, but I'm happy to assist whenever you have something for me test.

**Comment by scniro** [comment]
Hey again. So after re-reading this thread I made a super quick and dirty change to simple respect the `rebase: false`. As a result my tests appear to mimic the output as they did in 3.2.0. I packed up a tarball at https://github.com/scniro/gulp-clean-css-43 for you to try out in isolation before I publish anything to see if I can solve your issue. When you get the time, could you pull it down to test locally? Please share your findings. Thanks!

**Comment by sassy-ankit** [comment]
Does `isolatePipeline` option solved your issue? Its just last night I faced the same problem while using gulp-sass, especially in SUBLIME. I dont think `rebase:false` will do the trick. The issue is with the speed of _function execution_ and _file saving_ in the core `libsass` code, though dont want to disturb in your findings, keep posting what are your findings about `rebase `approach, or else I will share a quick turn around this issue.

**Comment by stephencorwin** [comment]
@scniro, I'm testing this locally, but it doesn't look like it is working. Can you verify what the change made was in the code? I'm not sure if it carried over in the tarball.

**Comment by scniro** [comment]
@stephencorwin hey, sorry if it's a wasted effort on your issue 😦 The change should respect `rebase: false` if passed in. @sassy-ankit thank you very much for exploring this as well. I can slate some time this weekend to squash the issue! Also, if feeling adventurous, feel free to submit a PR. Not at all necessary, just throwing it out there. Get back to you guys later on this weekend

**Comment by sassy-ankit** [comment]
@stephencorwin @scniro  
Consider the following code 
```
gulp.tasks('sass',function(){
	gulp.src("sass/*.sass")
	.pipe(sass())
	.pipe(autoprefix(
		'last 2 version','> 1%','ie 8','ie 9','ios 6','android 4'
	))
	.pipe(cleancss())
	.pipe(gulp.dest("build/css/"))
	.pipe(notfy({message: 'SASS processed!'}));
});
```
Also think of integrating gulp-concat and some other few. While executing of this, compiler pipelines everything on multiple of pipes. So if consider `sass()` execution before `.src` then it wont find a file to read. Thats why we get error `@import-file not found or unreadable`. To work around this, I found out three approaches.

Method 1) [Useless] performs only one thing in a single TASK. 
Method 2) [time consuming] add delay lengthy `.pipe` sources.
Method 3) [I use it in gulp, try to find the solution on this] `gulp-plumber`
What plumber does is it doesn't stop the execution even when any error occurs. e.g. `@import` error. and due to this fact, compiler re-attempt the code for execution on the later stage. Here is the code which I used.
```
gulp.tasks('sass',function(){
	gulp.src("sass/*.sass")
	.pipe(plumber())                                    // <<-------------------------------------------
	.pipe(sass())
	.pipe(autoprefix(
		'last 2 version','> 1%','ie 8','ie 9','ios 6','android 4'
	))
	.pipe(cleancss())
	.pipe(gulp.dest("build/css/"))
	.pipe(notfy({message: 'SASS processed!'}));
});
```
Hope @scniro, this finding may help you  to modify `clean-css` inherently.  

[Disclaimer: I am a newbie in developing but catching up fast.]

**Comment by stephencorwin** [comment]
@sassy-ankit
Forcing the use of another dependency (plumber) when it wasn't required before is not an acceptable solution in my opinion. It wasn't required before version 3.2.0. Any project looking to upgrade and use the latest version of gulp-clean-css should not need to rewrite their pipeline to use plumber.

To best support the direction that clean-css proper is going we should aim towards supporting the option **rebase: false** implicitly.

@scniro 
I'll take another shot at getting it to work locally over the weekend. Thanks again for your support.

**Comment by sassy-ankit** [comment]
@stephencorwin agree on your last comment. To keep my work going, i used this work around. If this insufficient method works, then may be you guys (the actual developers) can figure out something. Btw keep posting your findings, its a great resource for learners like me. Now on, I won't disturb the original conversation you guys have but will be following this thread closely. Thank you in advance for both of you.

**Comment by scniro** [comment]
@stephencorwin okay I tried again...

 - https://github.com/scniro/gulp-clean-css-43-2

This time the `rebase` option will still be configurable, _but_, I have reverted to the old way of passing in the direct styles opposed to the keyed file name object. The object will only be passed should one specify `rebaseTo`. Install and let me know?

**Comment by stephencorwin** [comment]
@scniro, I believe this is working.

**no rebase option set:**
`//rebaseTo: '/test/'`
![no-rebaseset](https://cloud.githubusercontent.com/assets/3931162/26316274/bd4bfdcc-3ee1-11e7-838d-f6f909fd6f87.PNG)

**rebaseTo option set:**
`rebaseTo: '/test/'`
![rebaseto](https://cloud.githubusercontent.com/assets/3931162/26316260/b2a93c0e-3ee1-11e7-8355-fc1a234d50b3.PNG)

I haven't used **rebaseTo** intentionally, before -- but I believe this output is correct.
If this change doesn't break any other tests, then I think we should be good to go.

**Comment by scniro** [comment]
@stephencorwin yep you should be good to go and I can publish up these changes this evening. Shouldn't affect anyone as passing the styles directly has always been the method I leveraged for 3.20 and before , but now for those who use `rebaseTo` - they internally opt for passing the keyed object. I'll comment here later on once I bump to npm and let you close it out once all looks good. I appreciate your efforts and the collaboration on this!

**Comment by scniro** [comment]
@stephencorwin @sassy-ankit  [3.4.0](https://github.com/scniro/gulp-clean-css/releases/tag/3.4.0) is not live and should be available to pull down via npm. Please let me know if you are squared away on this! Thanks.

**Comment by stephencorwin** [comment]
Thanks @scniro! I think we can close this issue out.

**Comment by sassy-ankit** [comment]
Thanx @scniro.
