### ISSUE TITLE
Multi-file merge bug

### ISSUE THREAD

**Issue by doocal** [scniro/gulp-clean-css#46]
gulp.src([
        './simple-line-icons.css',
        './font-awesome.css',
        './bootstrap.css'
    ]).pipe(minifyCss()))

source:
………………
url('fonts/fontawesome-webfont.woff2?v=4.4.0')
…………

compress：

……………… 
font-awesome --
url('../../fonts/fontawesome-webfont.woff2?v=4.4.0')
…………

The current file path is attached

**Comment by scniro** [comment]
This is quite a poor issue with lots of information missing and I am left to guess that you are expecting a different file path after processing. Look into [clean-css rebaseTo](https://github.com/jakubpawlowicz/clean-css#constructor-options)
