### ISSUE TITLE
Spaces removed from :not statement.

### ISSUE THREAD

**Issue by JParkinson1991** [scniro/gulp-clean-css#51]
Hello,

Ive noticed an issue with this package where spaces are removed from :not statements.
Im not 100% sure if this an issue with the gulp wrapper or the clean-css package it wraps.

Basically if i have css:
```
button {
    &:not(.gmap &){
        @include button();
    }
}
```

The compiled css becomes (notice the space removed from .gmap and button:
```
button:not(.gmapbutton){/* the mixin css */}
```

When using the following gulp process:
```
return gulp.src(cssPath + '/**/*.css')
        .pipe(groupMediaQueries())
        .pipe(cleanCss({
            compatibility: ie8,
            level: 2
        }))
        .pipe(gulp.dest(cssPath));
```

**Comment by scniro** [comment]
@JParkinson1991 Hello. Thanks for bringing this up. Unfortunately, any sort of minification specific oddities you are incurring in regards to the css itself should indeed be opened up on the [https://github.com/jakubpawlowicz/clean-css/issues](clean-css issue tracker). Sorry I can not help, but any changes in this repo won't affect your results in this case.
