### ISSUE TITLE
Level 1 optimization (default) and fonts with color keywords

### ISSUE THREAD

**Issue by nsciacca** [scniro/gulp-clean-css#54]
I'm trying to use the Google font "Crimson Text", however with the default optimization level the "Crimson" text is being replaced with its hex color equivalent "#dc143c" via the shorten-hex.js. Any thoughts on how to fix?

**Comment by scniro** [comment]
@nsciacca Please open up an issue over at [clean-css](https://github.com/jakubpawlowicz/clean-css) - this project is just a small wrapper around the core lib. Anything regarding rules and output discrepancies surely need to be discussed there.
