### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by inwardmovement** [scniro/gulp-clean-css#55]
Seems similar to [41](https://github.com/scniro/gulp-clean-css/issues/41) but not solved by [3.1.1](https://github.com/scniro/gulp-clean-css/releases/tag/3.1.1).

The plugin does not throw an error in local development (Windows), but does when building in production by Travis CI (Linux):

```
/home/travis/build/inwardmovement/inwardmovement.github.io/node_modules/gulp-clean-css/index.js:3
const applySourceMap = require('vinyl-sourcemaps-apply');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/inwardmovement/inwardmovement.github.io/gulpfile.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
The command "gulp" exited with 8.
```
I use `"gulp-clean-css": "^3.9.2"` and `npm 5.6.0`
Any idea how can I work around this?

**Comment by scniro** [comment]
Hmm, that's odd. I build this plugin on Travis myself and have no issues. The [source file](https://github.com/scniro/gulp-clean-css/blob/master/index.js#L1) is already in strict mode.

Actually, peeking at your build log, you're [using node version 0.10.48](https://travis-ci.org/inwardmovement/inwardmovement.github.io/jobs/345624269#L447). Umm, not good...

 [Just specify which engine](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) in your `.travis.yml`...

```
language: node_js
node_js:
  - "lts/*"

**Comment by inwardmovement** [comment]
Thanks, that did it!

I have another error then [in my log](https://travis-ci.org/inwardmovement/inwardmovement.github.io/builds/345761533), but not in the field of this issue.
