### ISSUE TITLE
Upgrading causes gigantic source maps.

### ISSUE THREAD

**Issue by tourniquet7** [scniro/gulp-clean-css#56]
I upgraded from 2.0.13 to 3.9.2 and now my sourcemaps are huge for the minified version. In package.json I have

"gulp-clean-css": "^3.9.2"
"gulp-sourcemaps": "^2.6.4"

Here is an excerpt from my gulp

```
gulp.task('build-css',() => {
	var streams = merge();
	buildPaths.forEach(function(sitepath){
		streams.add(gulp.src(path.join(rootPath, sitepath.cssinput))
	    .pipe(sourcemaps.init())
	    .pipe(sass()
	        .on('Error:', sass.logError))
	    .pipe(autoprefixer({
	        browsers: ['last 2 versions'],
	        cascade: false
	    }))
	    .pipe(sourcemaps.write('./'))
	    .pipe(chmod(777))
	    .pipe(gulp.dest(path.join(rootPath,sitepath.cssoutput))))
	});
	return streams;
});

gulp.task('build-min-css', ['build-css'],function(){
	var streams = merge();
	buildPaths.forEach(function(sitepath){
		streams.add(gulp.src(path.join(rootPath,sitepath.cssoutput + '/application' + sitepath.id + '.css'))
        .pipe(sourcemaps.init())
        .pipe(cleancss())
        .pipe(rename({extname: '.min.css'}))
        .pipe(sourcemaps.write('./'))
        .pipe(chmod(777))
        .pipe(gulp.dest(path.join(rootPath, sitepath.cssoutput))));
	});
	return streams;
});

```

The min sourcemaps were 1.3 mb now they are 130 mb.

**Comment by scniro** [comment]
Yikes, no idea. Have you looked into [gulp-sourcemaps](https://github.com/gulp-sourcemaps)? I don't mean to disregard this but I am missing a lot of information here other than quite a bit of time has bassed between your update. At that version, this plugin had a [sourcemap dep of 1.x](https://github.com/scniro/gulp-clean-css/commit/478edf8b187ba300d8977716f066a91975cc6844#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R48)

**Comment by tourniquet7** [comment]
When I change the version of sourcemaps to different versions there is no difference in the filesize of the map files. It only happens when I update gulp-clean-css. Not sure if its the culprit, its just what I've noticed.

**Comment by scniro** [comment]
My bad, that was a dev dep for testing, wow totally disregard what I said above. I really don't even know where to start looking, the only thing I notice is a 10x increase of 1.3 => 130. What does `var streams = merge();` do? Does your `forEach` happen to be 10 iterations? Could be a starting point to investigate the oddly suspicious increase.

**Comment by tourniquet7** [comment]
No worries! I'll just stick with the old version. I just figured I would let you know about it.

**Comment by scniro** [comment]
No, don't give up! I totally want to help you, I'm just probing to learn more is all. Can you share the details I'm looking for?

**Comment by scniro** [comment]
@tourniquet7 I'm going to close this for now. Please reopen should you wish to include some more details. Also FWIW there was a double [minor bump in gulp-sourcemaps](https://github.com/scniro/gulp-clean-css/commit/8479e19385de349e740a5dceb01e73a43de6401c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R49) in the last release as well as a [new version of clean-css](https://github.com/jakubpawlowicz/clean-css/releases/tag/v4.1.11). Could it help? Unsure, but could be worth looking at.
