### ISSUE TITLE
minor vulnerability in clean-css <4.1.11

### ISSUE THREAD

**Issue by GCDeveloper** [scniro/gulp-clean-css#57]
Please update clean-css to 4.1.11 or higher due to a minor vulnerability detailed here:
https://snyk.io/vuln/npm:clean-css:20180306

**Comment by scniro** [comment]
Thank you for bringing this to my attention. Will be fixed today and I'll post back here once it's published up.

**Comment by scniro** [comment]
@GCDeveloper fixed with the [3.9.3 release](https://github.com/scniro/gulp-clean-css/releases/tag/3.9.3)
