### ISSUE TITLE
clean-css options not working

### ISSUE THREAD

**Issue by ecnepsnai** [scniro/gulp-clean-css#58]
I'm having trouble disabling a specific rule for clean-css using gulp-clean-css, when I try my config out using the web interface: https://jakubpawlowicz.github.io/clean-css/ it works as intended but when I try it using gulp it doesn't work.

Here's the relevant gulp code:
```javascript
gulp.src(['./fonts/*.css'])
    .pipe(concat('fonts.css'))
    .pipe(cleanCSS({
        level: {
            1: {
                normalizeUrls: false
            }
        }
    }))
    .pipe(gulp.dest(BUILD_DIRECTORY_BASE + '/assets/css'));
```

I also tried:

```javascript
gulp.src(['./fonts/*.css'])
    .pipe(concat('fonts.css'))
    .pipe(cleanCSS({
        normalizeUrls: false
    }))
    .pipe(gulp.dest(BUILD_DIRECTORY_BASE + '/assets/css'));
```

As a troubleshooting step I also noticed that setting the level to 0 (which is supposed to disable all optimization) does nothing and still minifies the css

```javascript
gulp.src(['./fonts/*.css'])
    .pipe(concat('fonts.css'))
    .pipe(cleanCSS({
        level: 0
    }))
    .pipe(gulp.dest(BUILD_DIRECTORY_BASE + '/assets/css'));
```

I'm using `gulp-clean-css 3.9.3` on `node.js 9.5.0`

**Comment by scniro** [comment]
@ecnepsnai You appear to be using the clean-css API correctly, I have no idea why it wouldn't work for you as this plugin is just passing the options along. Can you throw together a small reproduction repo that uses the gulp plugin and the clean-css node api that demonstrates the difference in results?

**Comment by scniro** [comment]
@ecnepsnai closing as I find it unlikely that the options passed are not working - there would be droves of consumers here all reporting similar. Please reopen if you can add additional detail or demonstrate the problem.
