### ISSUE TITLE
libs word being replaced for css 

### ISSUE THREAD

**Issue by gbschalch** [scniro/gulp-clean-css#59]
Hi!

I have a .css file which contains a font file path (url) which has the "libs" word in it. After being processed by gulp clean css pipe, it's being replaced from "libs" to "css". Why?

Here's the pipe:

`gulp.task('create-static-css', ['clear'], function() {
  return gulp.src([sourceAssets+'libs/**/*.css', '!'+sourceAssets+'css/**/*.css'])
    .pipe(sourcemaps.init())
    .pipe(concat('static.css'))
    .pipe(autoprefixer('last 2 versions'))
    .pipe(rename({suffix:'.min'}))
    .pipe(minifycss())
    .pipe(sourcemaps.write('/maps'))
    .pipe(gulp.dest(buildAssets+'css/'))
});`

CSS declaration:
@font-face{font-family:Font Awesome\ 5 Brands;font-style:normal;font-weight:400;src:url(../libs/fontawesome/fa-brands-400.eot);

The path part results to:
../css/fontawesome/fa-brands-400.eot

--

Thanks in advance,

Guilherme Burger Schalch
Front End Developer

**Comment by TheDancingCode** [comment]
Does it still happen when you do `.pipe(minifycss({rebase: false}))`?

**Comment by scniro** [comment]
@gbschalch this is probably best to ask on [StackOverflow](https://stackoverflow.com/) as I suspect the issue could be specific to your implementation. You may also checking out [clean-css `rebaseTo`](https://github.com/jakubpawlowicz/clean-css#how-to-rebase-relative-image-urls) helpful in this situation
