### ISSUE TITLE
Error: Broken @import declaration .... - timeout

### ISSUE THREAD

**Issue by webdevinci** [scniro/gulp-clean-css#60]
When trying to retrieve Google fonts in our gulp build, it usually works fine. Sometimes it fails the first time, works the next. It is very important to us to not make those extra requests, so the processImports needs to be true.

My proposal would be to add a timeout property so it can goto whatever given option or default if not present.

**Comment by scniro** [comment]
@webdevinci unsure what you're proposing here or if I even understand the issue fully. Furthermore, I'd suspect the potential solution would be found within [clean-css](https://github.com/jakubpawlowicz/clean-css) itself. Closing for now but please reopen should you with to submit a PR or can provide more detail
