### ISSUE TITLE
Minification should be optional

### ISSUE THREAD

**Issue by sattes-faction** [scniro/gulp-clean-css#61]
Currently minification is enabled by default and cannot be disabled, this should be an option. Currently I can't just optimize a human-readable css without minification.

**Comment by scniro** [comment]
@sattes-faction PR's welcome! That should be fun simple one if you'd like to contribute 😸

**Comment by TheDancingCode** [comment]
Isn't `{format: 'beautify'}` doing what you want? See clean-css's [formatting options](https://github.com/jakubpawlowicz/clean-css#formatting-options).

**Comment by scniro** [comment]
@TheDancingCode ^nice find. I actually never knew that was an output option but yep, that should solve this one. I'll close this out if I don't hear back from the OP in a bit. Thanks for sharing that 👍

**Comment by sattes-faction** [comment]
@TheDancingCode : yeah, this works. Thank you!

@scniro : Thanks for your reply, I close this one - I should have RTFM. ;-)

**Comment by scniro** [comment]
@sattes-faction glad you're up and running now 😸 @TheDancingCode thanks again for your collaboration here
