### ISSUE TITLE
@import url('') deleted when minifying

### ISSUE THREAD

**Issue by emoc11** [scniro/gulp-clean-css#65]
Hi !

CleanCss made a [hot update 4.0.0](https://www.npmjs.com/package/clean-css#important-40-breaking-changes) that change the configuration...
For external @import to work you need to pass the configuration `inline: ['none']` or `inline: false` or `inline: ['local']`

So... We must have this configuration in your package too, to pass it to cleanCss after !

Is it possible to do this soon ?

Thanks !

**Comment by scniro** [comment]
@emoc11 so this package uses [clean-css@4.2.1](https://github.com/scniro/gulp-clean-css/blob/master/package.json#L32) which is the [most current release](https://github.com/jakubpawlowicz/clean-css/releases). 

You should be able to [pass the option](https://github.com/scniro/gulp-clean-css/blob/master/index.js#L35) here. Does passing the option not work as expected?

**Comment by emoc11** [comment]
It seems not i'm afraid...

Since 4.0 we can configure `inline: false` in cleanCss to be sure that it do nothing to @import but my `@import url("")` are still removed when i build with gulp-clean-css.. !

**Comment by scniro** [comment]
@emoc11 I was unable to track this down and am closing due to staleness. I have made various subsequent changes that may resolve your issue if you try to update. If the issue persists, please re-open a new issue with as much detail as possible and I'll help you look into it. Thanks!

**Comment by ivanff** [comment]
I have exactly the same problem as described by the author.
