### ISSUE TITLE
map.sources are already a relative path

### ISSUE THREAD

**Issue by canda** [scniro/gulp-clean-css#7]
Why is it that you are trying to make a relative path for sources.
In my case I'm receiving the correct relative path already on clean css callback
´´´
// src === "../sass/originalstylesheet.scss"
´´´
so when the map executes I get a source like
´´´
"../../../../../sass/wu-about-us-timeline.scss"
´´´
Is there a way to tell clean-css to return an absolute path for this?
Is it that clean-css changed or am I doing something wrong?

**Comment by scniro** [comment]
Was this an issue before? Is this new code on your end? Also, share your gulp code in question.

**Comment by canda** [comment]
Thanks for the quick response :)
I'm adding the sourcemaps now, so I can't tell if this was an issue before
```
gulp.task(tasks.compass, () => {
  return gulp.src([src + '/**/sass/'])
  // .pipe(debug({title: 'Running compass on'})) // For debugging
  .pipe(foreach((stream, folder) => {
    let folderPath = folder.path.replace(path.resolve(__dirname, '../'), '');

    return gulp.src('.' + folderPath + '/*.{scss,sass}')
    // .pipe(debug({title: 'Files'})) // For debugging
    .pipe(compass({
      config_file: './config.rb',
      bundle_exec: true,
      css: folder.path.replace('sass', 'css'),
      sass: folder.path,
      logging: false,
      comments: true
    }))
    .pipe(renameExtension('.min.css'))
    .pipe(sourcemaps.init())
    .pipe(minifyCSS({compatibility: 'ie8', relativeTo: './' }))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('.' + folderPath.replace('sass', 'css')));
  }));
});
```

**Comment by scniro** [comment]
@canda Hey there! So, I'm playing with some new stuff for a new version to publish, but I'm not heavy enough of a sourcemap user to really get down to the nitty gritty with the issues yourselves and others are experiencing. I'm trying to make the plugin less opinionated with sourcemaps, and letting clean-css under the hood take care of all the mapping.

My initial runs with it seem okay, but I'm wanting some more feedback before I'm confident to publish a new version. I made a new repo with a packaged version, [gulp-clean-css-test](https://github.com/scniro/gulp-clean-css-test). If you'd be willing, please clone this and install the packaged plugin into your project via `npm install ../path/to/this/repo/gulp-clean-css-2.1.0.tgz` and share any results you may have?

Also, if you're a command liner user of clean-css, can you compare the results of that with the plugin? If not, no worries. I am aiming for identical output so any sourcemapping issues aren't attributed to the specifics of this wrapper.

**Comment by scniro** [comment]
Check out [npm 2.1.0](https://www.npmjs.com/package/gulp-clean-css) and feel free to share your findings on here if it's now resolved

**Comment by scniro** [comment]
whirlwind of stuff today, try 2.1.3 please

**Comment by scniro** [comment]
more whirlwind => 2.2.0
