### ISSUE TITLE
Valid CSS be cleaned

### ISSUE THREAD

**Issue by Mess663** [scniro/gulp-clean-css#83]
`background: #222 url() center/cover no-repeat;`

Beacause of `url()`, this line will be cleaned

**Comment by scniro** [comment]
@Mess663 I've published the [4.3.0](https://github.com/scniro/gulp-clean-css/releases/tag/4.3.0) release. Unsure if this will solve any of the issues you are experiencing, but I suspect the root of the problem could be traced back to [clean-css](https://github.com/jakubpawlowicz/clean-css) itself. This lib is mostly a slim wrapper.
