### ISSUE TITLE
Sourcemaps in stream have their locations changed

### ISSUE THREAD

**Issue by jahumes** [scniro/gulp-clean-css#9]
We have run into a problem with our sourcemaps not being found when we run them through gulp-clean-css 2.0.7 or higher. We have tested this using node 5.10.1 and 6.2.2 and we have tested every version of gulp-clean-css from 2.0.7 - 2.0.12. The following error occurs in every case:

```
gulp build:client --prod
Mode:   Production
[10:25:52] Using gulpfile .../ui/gulpfile.js
[10:25:52] Starting 'clean:client'...
[10:25:52] Finished 'clean:client' after 8.15 ms
[10:25:52] Starting 'build:client'...
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.../ui/templates/build/styles/bootstrap-4cc48fd547.css.map'
  at Error (native)
  at Object.fs.openSync (fs.js:634:18)
  at Object.fs.readFileSync (fs.js:502:33)
  at fromSource (.../ui/node_modules/clean-css/lib/utils/input-source-map-tracker.js:84:30)
  at InputSourceMapStore.track (.../ui/node_modules/clean-css/lib/utils/input-source-map-tracker.js:237:5)
  at Object.whenDone (.../ui/node_modules/clean-css/lib/clean.js:145:44)
  at processNext (.../ui/node_modules/clean-css/lib/imports/inliner.js:105:13)
  at importFrom (.../ui/node_modules/clean-css/lib/imports/inliner.js:79:10)
  at ImportInliner.process (.../ui/node_modules/clean-css/lib/imports/inliner.js:38:10)
  at .../ui/node_modules/clean-css/lib/clean.js:120:41
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

We are taking multiple modules and building them out as separate files. Each file has it's own .map file and this is the one that seems to be not found. They end up in `/ui/public/build/styles/...` not the templates folder as see above.

Below is the gulp task and package.json. This is a large older code base, so some of it might be a little convoluted. ;)

``` js
var buildClient = lazypipe()
    .pipe($.useref,
        { searchPath: config.paths.files.libs },
        lazypipe().pipe($.sourcemaps.init, {loadMaps: true}),
        lazypipe().pipe(function() {
                return $.if('.less', styles()());
            }
        ))
    .pipe($.plumber)
    .pipe(function() {
        return $.if('*.js',scripts()());
    })
    .pipe(function() {
        return $.if('*.css',styles()());
    })
    .pipe($.sourcemaps.write, './')
    .pipe($.revReplace)
    .pipe(gulp.dest, config.paths.folders.public)
    .pipe($.rev.manifest, config.paths.files.manifest,{
        base: process.cwd() + '/' + config.paths.folders.build,
        merge: true
    })
    .pipe(gulp.dest, config.paths.folders.build);

gulp.task('build:client', ['clean:client'], function() {
    var isCompiled = options.prod && fs.existsSync(config.paths.files.manifest);
    var excludeFiles = function(filename) {
        if(_.includes([
                'build/scripts/simplifile.js',
                'build/scripts/vendor.js',
                'build/styles/vendor.css'
            ],filename)) {
            return 'excluded-text-that-should-not-be-found-in-the-file.js';
        }

        return filename;
    };

    return gulp.src(config.paths.files.views.main)
        .pipe($.if(isCompiled, $.revReplace({
            manifest: gulp.src('./' + config.paths.files.manifest),
            modifyUnreved: excludeFiles
        })))
        .pipe(buildClient())
});

function styles(templateName) {
    var isTemplateName = typeof templateName !== 'undefined';

    return lazypipe()
        .pipe(function() {
            return $.if('*.less', $.less({
                paths: ["src"],
                customFunctions: sfColorFunctions
            }).on('error', $.util.log));
        })
        .pipe(function() {
            return $.if(isTemplateName, $.concat(templateName + '.css'));
        })
        .pipe(function() {
            return $.if(options.prod, $.cleanCss())
        })
        .pipe(function() {
            return $.if(options.prod, $.rev())
        });
}

```

``` js
"dependencies": {
    "cheerio": "0.20.0",
    "colors": "0.6.2",
    "console.table": "0.7.0",
    "del": "2.2.1",
    "foreman": "0.4.2",
    "gulp-debug": "0.3.1",
    "gulp-filter": "0.5.1",
    "gulp-footer": "1.0.5",
    "gulp-header": "1.8.7",
    "gulp-load-plugins": "1.2.4",
    "gulp-rename": "1.2.2",
    "gulp-rev": "7.1.0",
    "gulp-rev-replace": "0.4.3",
    "gulp-sourcemaps": "0.4.6",
    "gulp-tap": "0.1.3",
    "gulp-useref": "3.1.0",
    "http-proxy": "1.14.0",
    "jsonfile": "2.3.1",
    "lazypipe": "1.0.1",
    "lodash": "4.13.1",
    "run-sequence": "0.3.7",
    "wiredep": "4.0.0",
    "wrench": "1.5.9",
    "yargs": "3.32.0"
  },
  "devDependencies": {
    "bower": "1.7.9",
    "eslint": "2.13.1",
    "eslint-config-angular": "0.5.0",
    "eslint-plugin-angular": "1.3.0",
    "event-stream": "3.3.4",
    "git-guppy": "=1.2.1",
    "gulp": "3.9.1",
    "gulp-cached": "1.1.0",
    "gulp-clean": "0.3.2",
    "gulp-clean-css": "2.0.7",
    "gulp-concat": "2.6.0",
    "gulp-concat-sourcemap": "1.3.1",
    "gulp-conflict": "0.4.0",
    "gulp-data": "1.2.1",
    "gulp-debug": "0.3.1",
    "gulp-directory-map": "0.1.3",
    "gulp-eslint": "2.1.0",
    "gulp-file": "0.3.0",
    "gulp-flatten": "0.2.0",
    "gulp-gitmodified": "1.1.1",
    "gulp-htmlmin": "1.3.0",
    "gulp-if": "2.0.1",
    "gulp-inject": "1.5.0",
    "gulp-inject-string": "1.1.0",
    "gulp-less": "file:lib-custom/gulp-less",
    "gulp-livereload": "2.1.1",
    "gulp-match": "1.0.2",
    "gulp-minify-html": "0.1.8",
    "gulp-ng-annotate": "0.5.3",
    "gulp-ng-html2js": "0.2.2",
    "gulp-plumber": "0.6.6",
    "gulp-rename": "1.2.2",
    "gulp-replace": "0.5.4",
    "gulp-shell": "0.5.2",
    "gulp-sort": "1.1.1",
    "gulp-sourcemaps": "0.4.6",
    "gulp-task-listing": "0.3.0",
    "gulp-template": "0.1.2",
    "gulp-tslint": "5.0.0",
    "gulp-typescript": "2.13.6",
    "gulp-uglify": "1.5.4",
    "gulp-util": "3.0.7",
    "gulp-watch": "4.3.8",
    "guppy-pre-commit": "0.3.0",
    "inquirer": "0.12.0",
    "jasmine-core": "2.4.1",
    "jasmine-promises": "0.4.1",
    "jasmine-reporters": "2.2.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "1.0.1",
    "karma-coffee-preprocessor": "1.0.1",
    "karma-coverage": "1.1.0",
    "karma-firefox-launcher": "1.0.0",
    "karma-html2js-preprocessor": "1.0.0",
    "karma-jasmine": "1.0.2",
    "karma-junit-reporter": "1.1.0",
    "karma-ng-scenario": "1.0.0",
    "karma-notification-reporter": "0.1.1",
    "karma-phantomjs-launcher": "1.0.1",
    "karma-requirejs": "1.0.0",
    "karma-script-launcher": "1.0.0",
    "karma-spec-reporter": "0.0.26",
    "main-bower-files": "2.13.1",
    "merge-stream": "1.0.0",
    "mkdirp": "0.5.1",
    "node-static": "0.7.7",
    "nopt": "2.2.1",
    "requirejs": "2.2.0",
    "run-sequence": "0.3.7",
    "through2": "2.0.1",
    "tslint": "3.11.0",
    "underscore.string": "2.4.0"
  }
```

**Comment by scniro** [comment]
Have you have a chance to peek at https://github.com/scniro/gulp-clean-css/issues/1 to see if it's related? Every issue opened seems to be related to sourcemaps and I'm thinking it's just an issue with gulp-sourcemaps with library files. Still unsure :\

**Comment by jahumes** [comment]
I did review #1 and it does not seemed directly related. What I think is happening is that because my map has a .css in the name, and is in the stream, the clean css is trying to modify it. But because the file hasn't been created yet, clean-css can't open it.

**Comment by almothafar** [comment]
+1

**Comment by scniro** [comment]
@jahumes if you can please create a small reproduction project of this I'll clone it and get a fix. Having trouble following your gulp task here with all the extra noise - needing just a bare-bones "this is the definitive problem" case.

**Comment by jahumes** [comment]
@scniro I will get that to you in the next couple of days. Thanks for working on this!

**Comment by scniro** [comment]
@jahumes no thank you! My apologies for delaying this wayyy too long. I'll keep an eye out to hear back from ya :smile: Until then, were you able to hack a workaround or has this still been a thorn in your side?

**Comment by jahumes** [comment]
@scniro I have done a little more research and can say it is https://github.com/scniro/gulp-clean-css/commit/f62380bcffe1b4b57b0c07927cb1ac9cf50e0f80 that breaks the task. I am using [gulp-useref](https://github.com/jonkemp/gulp-useref) to concat files and gulp-sourcemaps to build the sourcemaps. It appears that because the sourcemaps are being created before the concatenation but this plugin is being called after, the sourcemaps in the stream no have references to their sourcemaps (pure guess).

**Comment by scniro** [comment]
@jahumes okay cool I'm digging into this a bit now. So you can confirm there was no issue before that change? I put that in place for a bug with node 6 dropping, but everything seemed to retro just fine with all versions of node :/

**Comment by scniro** [comment]
@jahumes  Hey there! So, I'm playing with some new stuff for a new version to publish, but I'm not heavy enough of a sourcemap user to really get down to the nitty gritty with the issues yourselves and others are experiencing. I'm trying to make the plugin less opinionated with sourcemaps, and letting clean-css under the hood take care of all the mapping.

My initial runs with it seem okay, but I'm wanting some more feedback before I'm confident to publish a new version. I made a new repo with a packaged version, [gulp-clean-css-test](https://github.com/scniro/gulp-clean-css-test). If you'd be willing, please clone this and install the packaged plugin into your project via `npm install ../path/to/this/repo/gulp-clean-css-2.1.0.tgz` and share any results you may have?

Also, if you're a command liner user of clean-css, can you compare the results of that with the plugin? If not, no worries. I am aiming for identical output so any sourcemapping issues aren't attributed to the specifics of this wrapper.

**Comment by alexmchardy** [comment]
I'm seeing the same sort of behavior as @jahumes:
```
Error: ENOENT: no such file or directory, open '.../maps/bootstrap-custom.css.map'
```
I tried two things that might provide some data points for your investigation.
 - Installed the tarball mentioned above ([gulp-clean-css-test](https://github.com/scniro/gulp-clean-css-test)). This version of the code seemed to suffer from the same problem (unable to open `bootstrap-custom.css.map`).
 - Manually reverted https://github.com/scniro/gulp-clean-css/commit/f62380bcffe1b4b57b0c07927cb1ac9cf50e0f80 mentioned by @jahumes above. This seemed to fix the issue and produce a valid sourcemap. 

FWIW, the `sourceMap` option of CleanCSS [expects a string according to the docs](https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-api), so I don't see how the change from that commit (adding `JSON.parse`) should work.

**Comment by scniro** [comment]
@alexmchardy I'm trying to reproduce this on my end and simply can not. Can someone please package together a very small project which reproduces this?

**Comment by alexmchardy** [comment]
@scniro I attempted to build a simple repo reproducing the problem: https://github.com/alexmchardy/gulp-clean-css-sourcemap-issue

Strange thing is, I got the problem to happen twice (on `$(npm bin)/gulp step2`) and then it stopped happening. Here's the output from one of the two times it happened:
```
$ gulp step2
[17:03:41] Using gulpfile ~/src/tmp/gulp-clean-css-sourcemap-issue/gulpfile.js
[17:03:41] Starting 'step2'...
[17:03:41] Finished 'step2' after 15 ms
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: ENOENT: no such file or directory, open '/Users/amchardy/src/tmp/gulp-clean-css-sourcemap-issue/maps/a.css.map'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at fromSource (/Users/amchardy/src/tmp/gulp-clean-css-sourcemap-issue/node_modules/gulp-clean-css/node_modules/clean-css/lib/utils/input-source-map-tracker.js:84:30)
    at InputSourceMapStore.track (/Users/amchardy/src/tmp/gulp-clean-css-sourcemap-issue/node_modules/gulp-clean-css/node_modules/clean-css/lib/utils/input-source-map-tracker.js:237:5)
    at Object.whenDone (/Users/amchardy/src/tmp/gulp-clean-css-sourcemap-issue/node_modules/gulp-clean-css/node_modules/clean-css/lib/clean.js:145:44)
    at processNext (/Users/amchardy/src/tmp/gulp-clean-css-sourcemap-issue/node_modules/gulp-clean-css/node_modules/clean-css/lib/imports/inliner.js:105:13)
    at importFrom (/Users/amchardy/src/tmp/gulp-clean-css-sourcemap-issue/node_modules/gulp-clean-css/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at ImportInliner.process (/Users/amchardy/src/tmp/gulp-clean-css-sourcemap-issue/node_modules/gulp-clean-css/node_modules/clean-css/lib/imports/inliner.js:38:10)
    at /Users/amchardy/src/tmp/gulp-clean-css-sourcemap-issue/node_modules/gulp-clean-css/node_modules/clean-css/lib/clean.js:120:41
```
I've tried everything I can think of to make it happen again with no luck, spending way more time on it than I should have. I believe `gulpfile.js` in that repo is in the state at which the issue occurred. I tried installing various versions of `gulp-clean-css`, `clean-css` (underneath `gulp-clean-css`), `gulp-sourcemaps`, and `gulp` with no effect (the build keeps working).

Feel free to clone [alexmchardy/gulp-clean-css-sourcemap-issue](https://github.com/alexmchardy/gulp-clean-css-sourcemap-issue) and give it a try yourself.

**Comment by scniro** [comment]
@alexmchardy excellent, thank you very much, I will look into this tomorrow and get back to you with my findings!! :smile_cat:

**Comment by scniro** [comment]
@alexmchardy so, I too was getting weird behavior, but I think the issue is with your gulp tasks themselves. Firstly, since the `step2` task is reading files which already have a sourcemap to them and we are "re-sourcemapping" it appears to help if we specify the following `.pipe(sourcemaps.init({loadMaps: true}))`. Secondly, you are not returning in the tasks. When I compose the following with a clean dependency order, I seem to build without issue...

```
gulp.task('clean', function (done) {
    del.sync(['dist/']); // housekeeping
    done();
});

gulp.task('step1', ['clean'], function () {
     return gulp.src('a.scss')
        .pipe(sourcemaps.init())
        .pipe(sass().on('error', sass.logError))
        .pipe(sourcemaps.write('maps'))
        .pipe(gulp.dest('dist'));
});

gulp.task('step2', ['step1'], function () {
     return gulp.src(['dist/a.css', 'b.css'])
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(concat('final.css'))
        .pipe(cleanCss())
        .pipe(sourcemaps.write('maps'))
        .pipe(gulp.dest('dist'));
});

gulp.task('default', ['step2']);
```

Removing `return` indeed throws the error you are getting. Also, I was playing with the [gulp-sourcemaps write options](https://github.com/floridoo/gulp-sourcemaps#write-options), all of which altered my map sources in regards to file paths. Since you are hosting these yourself via `.write('maps')` - perhaps it's worthwhile to play with these options and examine your results.

Hope this is of at least some help

**Comment by jp7677** [comment]
Hi there, not sure if this is related, but I had some issues with sourcemaps and gulp-clean-css as well (Error: ENOENT: no such file or directory, open ' [......]src/css/bootstrap.css.map'). Tuns out all was well after specifying `sourceMap: false` as clean-css argument. Somehow the sourcemap magic within clean-css still wants to do some work while I actually only want gulp-sourcemaps to do the job. My gulp magic (important pieces):

```
var srcCss = [
    paths.src + '**/css/bootstrap.css',
    paths.src + '**/css/bootstrap-theme.css',
    paths.src + '**/css/font-awesome.css',
    paths.src + 'css/*'
  ]
  return gulp.src(srcCss)
    .pipe(sourcemaps.init())
    .pipe(concat('app-bundle.css'))
    .pipe(cleancss({keepSpecialComments: 0, sourceMap: false}))
    .pipe(sourcemaps.write('.', {
      mapSources: function (sourcePath) {
        var prefix = ''
        if (sourcePath.indexOf('/') === -1) {
          prefix = 'css/'
        }
        var extendedSourcePath = paths.src.substr(2) + prefix + sourcePath
        util.log('SourcePath within source map extended to:', util.colors.cyan(extendedSourcePath))
        return extendedSourcePath
      }
    }))
    .pipe(gulp.dest(paths.wwwroot))
```

Note that I'm using gulp-sourcemaps ~2.0.0-alpha.

Hope this somehow helps.

**Comment by jvivs** [comment]
I addressed this issue by passing `{loadMaps: true}` to `gulp-sourcemap` before consuming the css file in a different directory: https://www.npmjs.com/package/gulp-sourcemaps#init-options

**Comment by scniro** [comment]
Hey everyone I changed some stuff around and published [2.1.0](https://www.npmjs.com/package/gulp-clean-css). Still can't pinpoint this, but maybe it's fixed. Feel free to share your findings here

**Comment by scniro** [comment]
whirlwind of stuff today, try 2.1.3 please

**Comment by scniro** [comment]
more whirlwind => 2.2.0
